#!/usr/bin/env python3
"""
sync-models.py — Dynamic Model Selection for Claude Code
Fetches real-time benchmark data from aistupidlevel.info and updates
~/.claude/model-env.sh with the best-performing Opus and Sonnet versions.

Designed to run via cron every hour:
  0 * * * * python3 /path/to/sync-models.py

Algorithm:
  1. Filter: Remove models with critical degradation or low 7d average (< 55)
  2. Rank: Sort by currentScore (real-time, changes hourly)
  3. Hysteresis: Only switch if new best is 5+ points better (prevents flip-flop)
"""

import json
import os
import sys
import urllib.request
import urllib.error
from datetime import datetime, timezone
from pathlib import Path

# --- Configuration ---
API_BASE = "https://aistupidlevel.info/api"
MODEL_ENV_PATH = Path.home() / ".claude" / "model-env.sh"
MIN_PERIOD_AVG = 55        # Minimum 7d average to qualify
HYSTERESIS_THRESHOLD = 5   # Must be N points better to trigger switch
VENDOR = "anthropic"

# --- API Helpers ---
def fetch_json(endpoint: str) -> dict | None:
    """Fetch JSON from API. Returns None on failure."""
    url = f"{API_BASE}/{endpoint}"
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "sync-models/1.0"})
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read().decode())
    except (urllib.error.URLError, json.JSONDecodeError, TimeoutError) as e:
        print(f"[WARN] Failed to fetch {url}: {e}", file=sys.stderr)
        return None

# --- Core Logic ---
def get_degraded_models(degradations: list) -> set:
    """Extract model IDs with critical degradation."""
    return {
        str(d["modelId"])
        for d in degradations
        if d.get("severity") == "critical"
    }

def get_current_models() -> tuple[str | None, str | None]:
    """Read currently configured models from model-env.sh."""
    opus, sonnet = None, None
    if MODEL_ENV_PATH.exists():
        for line in MODEL_ENV_PATH.read_text().splitlines():
            if "ANTHROPIC_DEFAULT_OPUS_MODEL=" in line:
                opus = line.split("=", 1)[1].strip().strip("'\"")
            elif "ANTHROPIC_DEFAULT_SONNET_MODEL=" in line:
                sonnet = line.split("=", 1)[1].strip().strip("'\"")
    return opus, sonnet

def select_best(models: list, degraded_ids: set, current_name: str | None, prefix: str) -> dict | None:
    """
    Select the best model for a given prefix (claude-opus- or claude-sonnet-).
    
    1. Filter by vendor + name prefix
    2. Exclude critical degradation
    3. Exclude models with periodAvg < MIN_PERIOD_AVG
    4. Sort by currentScore
    5. Apply hysteresis: keep current if new best is within threshold
    """
    candidates = [
        m for m in models
        if m.get("provider") == VENDOR
        and m["name"].startswith(prefix)
        and str(m["id"]) not in degraded_ids
        and m.get("periodAvg", 0) >= MIN_PERIOD_AVG
    ]
    
    if not candidates:
        return None
    
    # Sort by currentScore descending
    candidates.sort(key=lambda m: m.get("currentScore", 0), reverse=True)
    best = candidates[0]
    
    # Hysteresis: if currently using a model, only switch if improvement > threshold
    if current_name:
        current = next((m for m in candidates if m["name"] == current_name), None)
        if current:
            diff = best["currentScore"] - current["currentScore"]
            if diff <= HYSTERESIS_THRESHOLD:
                return current  # Keep current, not enough improvement
    
    return best

def write_model_env(opus_name: str, sonnet_name: str, opus_score: int, sonnet_score: int):
    """Write environment variables to ~/.claude/model-env.sh (sourced via .bashrc for CLI)."""
    MODEL_ENV_PATH.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    content = f"""# Auto-generated by sync-models.py — DO NOT EDIT MANUALLY
# Updated: {now}
# Opus: {opus_name} (score: {opus_score})
# Sonnet: {sonnet_name} (score: {sonnet_score})
export ANTHROPIC_DEFAULT_OPUS_MODEL='{opus_name}'
export ANTHROPIC_DEFAULT_SONNET_MODEL='{sonnet_name}'
"""
    MODEL_ENV_PATH.write_text(content)

# --- Main ---
def main():
    # 1. Fetch data
    scores_data = fetch_json("dashboard/scores?period=7d")
    degradation_data = fetch_json("analytics/degradations")
    
    if not scores_data or not scores_data.get("success"):
        print("[ERROR] Failed to fetch scores. Keeping existing config.", file=sys.stderr)
        sys.exit(1)
    
    models = scores_data["data"]
    degradations = degradation_data.get("data", []) if degradation_data and degradation_data.get("success") else []
    degraded_ids = get_degraded_models(degradations)
    
    # 2. Get current configuration
    current_opus, current_sonnet = get_current_models()
    
    # 3. Select best models
    best_opus = select_best(models, degraded_ids, current_opus, "claude-opus-")
    best_sonnet = select_best(models, degraded_ids, current_sonnet, "claude-sonnet-")
    
    if not best_opus or not best_sonnet:
        print("[ERROR] No qualified models found. Keeping existing config.", file=sys.stderr)
        sys.exit(1)
    
    opus_name = best_opus["name"]
    sonnet_name = best_sonnet["name"]
    opus_score = best_opus["currentScore"]
    sonnet_score = best_sonnet["currentScore"]
    
    # 4. Write result
    write_model_env(opus_name, sonnet_name, opus_score, sonnet_score)
    
    # 5. Log
    changed_opus = "→ CHANGED" if opus_name != current_opus else "(unchanged)"
    changed_sonnet = "→ CHANGED" if sonnet_name != current_sonnet else "(unchanged)"
    
    print(f"[sync-models] Opus:   {opus_name} (score={opus_score}) {changed_opus}")
    print(f"[sync-models] Sonnet: {sonnet_name} (score={sonnet_score}) {changed_sonnet}")
    print(f"[sync-models] Written to {MODEL_ENV_PATH}")

if __name__ == "__main__":
    main()
